// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CustomizationMcps():Promise<Array<main.desktopCatalogItem>>;

export function CustomizationRules():Promise<Array<main.desktopRule>>;

export function CustomizationSkills():Promise<Array<main.desktopCatalogItem>>;

export function CustomizationSubagents():Promise<Array<main.desktopCatalogItem>>;

export function DeleteCustomizationRule(arg1:number):Promise<Array<main.desktopRule>>;

export function DeleteCustomizationSubagent(arg1:string):Promise<Array<main.desktopCatalogItem>>;

export function ProjectSidebarData():Promise<main.desktopSidebarData>;

export function ReorderCustomizationRules(arg1:Array<number>):Promise<Array<main.desktopRule>>;

export function RolesTable():Promise<main.desktopRolesTable>;

export function SaveRolesTable(arg1:Array<string>):Promise<main.desktopRolesTable>;

export function SaveUserName(arg1:string):Promise<string>;

export function UpdateCustomizationRule(arg1:number,arg2:string):Promise<Array<main.desktopRule>>;

export function UpdateCustomizationSubagent(arg1:string,arg2:string,arg3:Array<main.desktopScorePatch>):Promise<Array<main.desktopCatalogItem>>;
