// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {research} from '../models';

export function AtMentionSuggestions(arg1:Array<main.desktopAtMentionEntry>,arg2:string):Promise<Array<main.desktopAtMentionSuggestion>>;

export function CheckoutProjectBranch(arg1:string,arg2:string):Promise<main.desktopProjectBranches>;

export function ConnectProvider(arg1:main.desktopConnectProviderRequest):Promise<main.desktopModelChoice>;

export function CustomizationMcps():Promise<Array<main.desktopCatalogItem>>;

export function CustomizationPromptTemplate(arg1:string):Promise<main.desktopPromptTemplate>;

export function CustomizationPromptTemplates():Promise<Array<main.desktopCatalogItem>>;

export function CustomizationRules():Promise<Array<main.desktopRule>>;

export function CustomizationSkills():Promise<Array<main.desktopCatalogItem>>;

export function CustomizationSubagents():Promise<Array<main.desktopCatalogItem>>;

export function DeleteCustomizationRule(arg1:number):Promise<Array<main.desktopRule>>;

export function DeleteCustomizationSubagent(arg1:string):Promise<Array<main.desktopCatalogItem>>;

export function HomeDirectoryEntries(arg1:string):Promise<Array<main.desktopProjectDirectoryEntry>>;

export function ModelCatalog():Promise<main.desktopModelCatalog>;

export function ProjectAtMentionSuggestions(arg1:string,arg2:string):Promise<Array<main.desktopAtMentionSuggestion>>;

export function ProjectBranches(arg1:string):Promise<main.desktopProjectBranches>;

export function ProjectDirectoryEntries(arg1:string,arg2:string):Promise<Array<main.desktopProjectDirectoryEntry>>;

export function ProjectGitHistory(arg1:string):Promise<main.desktopProjectGitHistory>;

export function ProjectGitStatus(arg1:string):Promise<main.desktopProjectGitStatus>;

export function ProjectRemovalInfo(arg1:string):Promise<main.desktopProjectRemovalInfo>;

export function ProjectResearch(arg1:string):Promise<Array<research.JobRecord>>;

export function ProjectResearchReport(arg1:string,arg2:string):Promise<string>;

export function ProjectSidebarData():Promise<main.desktopSidebarData>;

export function ProjectWorktrees(arg1:string):Promise<main.desktopProjectWorktrees>;

export function RemoveProjectFromDisk(arg1:string):Promise<void>;

export function RemoveProjectFromSidebar(arg1:string):Promise<void>;

export function ReorderCustomizationRules(arg1:Array<number>):Promise<Array<main.desktopRule>>;

export function ResetCustomizationPromptTemplate(arg1:string):Promise<main.desktopPromptTemplate>;

export function RolesTable():Promise<main.desktopRolesTable>;

export function SaveCurrentModel(arg1:string,arg2:string):Promise<main.desktopModelChoice>;

export function SaveReasoningEffort(arg1:string):Promise<string>;

export function SaveRolesTable(arg1:Array<string>):Promise<main.desktopRolesTable>;

export function SaveUserName(arg1:string):Promise<string>;

export function SetModelEnabled(arg1:string,arg2:string,arg3:boolean):Promise<main.desktopModelVisibility>;

export function UpdateCustomizationPromptTemplate(arg1:string,arg2:string):Promise<main.desktopPromptTemplate>;

export function UpdateCustomizationRule(arg1:number,arg2:string):Promise<Array<main.desktopRule>>;

export function UpdateCustomizationSubagent(arg1:string,arg2:string,arg3:Array<main.desktopScorePatch>):Promise<Array<main.desktopCatalogItem>>;
