// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AtMentionSuggestions(arg1, arg2) {
  return window['go']['main']['DesktopBridge']['AtMentionSuggestions'](arg1, arg2);
}

export function CheckoutProjectBranch(arg1, arg2) {
  return window['go']['main']['DesktopBridge']['CheckoutProjectBranch'](arg1, arg2);
}

export function ConnectProvider(arg1) {
  return window['go']['main']['DesktopBridge']['ConnectProvider'](arg1);
}

export function CustomizationMcps() {
  return window['go']['main']['DesktopBridge']['CustomizationMcps']();
}

export function CustomizationPromptTemplate(arg1) {
  return window['go']['main']['DesktopBridge']['CustomizationPromptTemplate'](arg1);
}

export function CustomizationPromptTemplates() {
  return window['go']['main']['DesktopBridge']['CustomizationPromptTemplates']();
}

export function CustomizationRules() {
  return window['go']['main']['DesktopBridge']['CustomizationRules']();
}

export function CustomizationSkills() {
  return window['go']['main']['DesktopBridge']['CustomizationSkills']();
}

export function CustomizationSubagents() {
  return window['go']['main']['DesktopBridge']['CustomizationSubagents']();
}

export function DeleteCustomizationRule(arg1) {
  return window['go']['main']['DesktopBridge']['DeleteCustomizationRule'](arg1);
}

export function DeleteCustomizationSubagent(arg1) {
  return window['go']['main']['DesktopBridge']['DeleteCustomizationSubagent'](arg1);
}

export function ModelCatalog() {
  return window['go']['main']['DesktopBridge']['ModelCatalog']();
}

export function ProjectAtMentionSuggestions(arg1, arg2) {
  return window['go']['main']['DesktopBridge']['ProjectAtMentionSuggestions'](arg1, arg2);
}

export function ProjectBranches(arg1) {
  return window['go']['main']['DesktopBridge']['ProjectBranches'](arg1);
}

export function ProjectDirectoryEntries(arg1, arg2) {
  return window['go']['main']['DesktopBridge']['ProjectDirectoryEntries'](arg1, arg2);
}

export function ProjectGitHistory(arg1) {
  return window['go']['main']['DesktopBridge']['ProjectGitHistory'](arg1);
}

export function ProjectGitStatus(arg1) {
  return window['go']['main']['DesktopBridge']['ProjectGitStatus'](arg1);
}

export function ProjectRemovalInfo(arg1) {
  return window['go']['main']['DesktopBridge']['ProjectRemovalInfo'](arg1);
}

export function ProjectResearch(arg1) {
  return window['go']['main']['DesktopBridge']['ProjectResearch'](arg1);
}

export function ProjectResearchReport(arg1, arg2) {
  return window['go']['main']['DesktopBridge']['ProjectResearchReport'](arg1, arg2);
}

export function ProjectSidebarData() {
  return window['go']['main']['DesktopBridge']['ProjectSidebarData']();
}

export function ProjectWorktrees(arg1) {
  return window['go']['main']['DesktopBridge']['ProjectWorktrees'](arg1);
}

export function RemoveProjectFromDisk(arg1) {
  return window['go']['main']['DesktopBridge']['RemoveProjectFromDisk'](arg1);
}

export function RemoveProjectFromSidebar(arg1) {
  return window['go']['main']['DesktopBridge']['RemoveProjectFromSidebar'](arg1);
}

export function ReorderCustomizationRules(arg1) {
  return window['go']['main']['DesktopBridge']['ReorderCustomizationRules'](arg1);
}

export function ResetCustomizationPromptTemplate(arg1) {
  return window['go']['main']['DesktopBridge']['ResetCustomizationPromptTemplate'](arg1);
}

export function RolesTable() {
  return window['go']['main']['DesktopBridge']['RolesTable']();
}

export function SaveCurrentModel(arg1, arg2) {
  return window['go']['main']['DesktopBridge']['SaveCurrentModel'](arg1, arg2);
}

export function SaveReasoningEffort(arg1) {
  return window['go']['main']['DesktopBridge']['SaveReasoningEffort'](arg1);
}

export function SaveRolesTable(arg1) {
  return window['go']['main']['DesktopBridge']['SaveRolesTable'](arg1);
}

export function SaveUserName(arg1) {
  return window['go']['main']['DesktopBridge']['SaveUserName'](arg1);
}

export function SetModelEnabled(arg1, arg2, arg3) {
  return window['go']['main']['DesktopBridge']['SetModelEnabled'](arg1, arg2, arg3);
}

export function UpdateCustomizationPromptTemplate(arg1, arg2) {
  return window['go']['main']['DesktopBridge']['UpdateCustomizationPromptTemplate'](arg1, arg2);
}

export function UpdateCustomizationRule(arg1, arg2) {
  return window['go']['main']['DesktopBridge']['UpdateCustomizationRule'](arg1, arg2);
}

export function UpdateCustomizationSubagent(arg1, arg2, arg3) {
  return window['go']['main']['DesktopBridge']['UpdateCustomizationSubagent'](arg1, arg2, arg3);
}
