// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ModelCatalog() {
  return window['go']['main']['DesktopBridge']['ModelCatalog']();
}

export function CustomizationMcps() {
  return window['go']['main']['DesktopBridge']['CustomizationMcps']();
}

export function CustomizationRules() {
  return window['go']['main']['DesktopBridge']['CustomizationRules']();
}

export function CustomizationSkills() {
  return window['go']['main']['DesktopBridge']['CustomizationSkills']();
}

export function CustomizationSubagents() {
  return window['go']['main']['DesktopBridge']['CustomizationSubagents']();
}

export function DeleteCustomizationRule(arg1) {
  return window['go']['main']['DesktopBridge']['DeleteCustomizationRule'](arg1);
}

export function DeleteCustomizationSubagent(arg1) {
  return window['go']['main']['DesktopBridge']['DeleteCustomizationSubagent'](arg1);
}

export function ProjectSidebarData() {
  return window['go']['main']['DesktopBridge']['ProjectSidebarData']();
}

export function ReorderCustomizationRules(arg1) {
  return window['go']['main']['DesktopBridge']['ReorderCustomizationRules'](arg1);
}

export function RolesTable() {
  return window['go']['main']['DesktopBridge']['RolesTable']();
}

export function SaveRolesTable(arg1) {
  return window['go']['main']['DesktopBridge']['SaveRolesTable'](arg1);
}

export function SaveCurrentModel(arg1, arg2) {
  return window['go']['main']['DesktopBridge']['SaveCurrentModel'](arg1, arg2);
}

export function SaveReasoningEffort(arg1) {
  return window['go']['main']['DesktopBridge']['SaveReasoningEffort'](arg1);
}

export function SaveUserName(arg1) {
  return window['go']['main']['DesktopBridge']['SaveUserName'](arg1);
}

export function UpdateCustomizationRule(arg1, arg2) {
  return window['go']['main']['DesktopBridge']['UpdateCustomizationRule'](arg1, arg2);
}

export function UpdateCustomizationSubagent(arg1, arg2, arg3) {
  return window['go']['main']['DesktopBridge']['UpdateCustomizationSubagent'](arg1, arg2, arg3);
}
